const shrimp = [
    {
        imageSrc: require("../ShrimpShots/Isopod/LovePotion-1.jpg"),
        name: "Japanese Magic Potion",
        description: '(Armadillidium)',
        border: {borderImage: 'linear-gradient(#83a6dd , #7a8273) 1'},
    },
    {
        imageSrc: require("../ShrimpShots/Isopod/Zebra-1.jpg"),
        name: "Zebra",
        description: '(Porcellio)',
        border: {borderImage: 'linear-gradient(#83a6dd , #150f36) 1'},
    },
    {
        imageSrc: require("../ShrimpShots/Isopod/Blonde_Ducky.jpg"),
        name: "Blonde Ducky",
        description: '(Porcellio)',
        border: {borderImage: 'linear-gradient(#83a6dd , #150f36) 1'},
    },
    {
        imageSrc: require("../ShrimpShots/Isopod/Black_Dalmation.jpg"),
        name: "Black Dalmation",
        description: '(Cubaris)',
        border: {borderImage: 'linear-gradient(#83a6dd , #150f36) 1'},
    },
    {
        imageSrc: require("../ShrimpShots/Isopod/Bolivari.jpg"),
        name: "Bolivari",
        description: '(Porcellio)',
        border: {borderImage: 'linear-gradient(#83a6dd , #150f36) 1'},
    },
    {
        imageSrc: require("../ShrimpShots/Isopod/Clown.jpg"),
        name: "Clown",
        description: '(Armadillidium)',
        border: {borderImage: 'linear-gradient(#83a6dd , #150f36) 1'},
    },
    {
        imageSrc: require("../ShrimpShots/Isopod/Granulatum.jpg"),
        name: "Granulatum",
        description: '(Armadillidium)',
        border: {borderImage: 'linear-gradient(#83a6dd , #150f36) 1'},
    },
    {
        imageSrc: require("../ShrimpShots/Isopod/Laevis.jpg"),
        name: "Laevis",
        description: '(Porcellio)',
        border: {borderImage: 'linear-gradient(#83a6dd , #150f36) 1'},
    },
    {
        imageSrc: require("../ShrimpShots/Isopod/Lava.jpg"),
        name: "Lava",
        description: '(Porcellio)',
        border: {borderImage: 'linear-gradient(#83a6dd , #150f36) 1'},
    },
    {
        imageSrc: require("../ShrimpShots/Isopod/Little_Sea.jpg"),
        name: "Little Sea",
        description: '(Cubaris)',
        border: {borderImage: 'linear-gradient(#83a6dd , #150f36) 1'},
    },
    {
        imageSrc: require("../ShrimpShots/Isopod/Magic_Potion.jpg"),
        name: "Magic Potion",
        description: '(Armadillidium)',
        border: {borderImage: 'linear-gradient(#83a6dd , #150f36) 1'},
    },
    {
        imageSrc: require("../ShrimpShots/Isopod/Marbelized.jpg"),
        name: "Marbelized",
        description: '(Armadillidium)',
        border: {borderImage: 'linear-gradient(#83a6dd , #150f36) 1'},
    },
    {
        imageSrc: require("../ShrimpShots/Isopod/Milkback.jpg"),
        name: "Milkback",
        description: '(Porcellio)',
        border: {borderImage: 'linear-gradient(#83a6dd , #150f36) 1'},
    },
    {
        imageSrc: require("../ShrimpShots/Isopod/Morocco.jpg"),
        name: "Morocco",
        description: '(Porcellio)',
        border: {borderImage: 'linear-gradient(#83a6dd , #150f36) 1'},
    },
    {
        imageSrc: require("../ShrimpShots/Isopod/Orange_Koi.jpg"),
        name: "Orange Koi",
        description: '(Porcellio)',
        border: {borderImage: 'linear-gradient(#83a6dd , #150f36) 1'},
    },
    {
        imageSrc: require("../ShrimpShots/Isopod/Orange_Dalmation.jpg"),
        name: "Orange Dalmation",
        description: '(Porcellio)',
        border: {borderImage: 'linear-gradient(#83a6dd , #150f36) 1'},
    },
    {
        imageSrc: require("../ShrimpShots/Isopod/Orange_Vigor.jpg"),
        name: "Orange Vigor",
        description: '(Armadillidium)',
        border: {borderImage: 'linear-gradient(#83a6dd , #150f36) 1'},
    },
    {
        imageSrc: require("../ShrimpShots/Isopod/Pack_Chong.jpg"),
        name: "Pack Chong",
        description: '(Cubaris)',
        border: {borderImage: 'linear-gradient(#83a6dd , #150f36) 1'},
    },
    {
        imageSrc: require("../ShrimpShots/Isopod/Panda_King.jpg"),
        name: "Panda King",
        description: '(Cubaris)',
        border: {borderImage: 'linear-gradient(#83a6dd , #150f36) 1'},
    },
    {
        imageSrc: require("../ShrimpShots/Isopod/Paraccae.jpg"),
        name: "Paraccae",
        description: '(Armadillidium)',
        border: {borderImage: 'linear-gradient(#83a6dd , #150f36) 1'},
    },
    {
        imageSrc: require("../ShrimpShots/Isopod/Peach.jpg"),
        name: "Peach",
        description: '(Armadillidium)',
        border: {borderImage: 'linear-gradient(#83a6dd , #150f36) 1'},
    },
    {
        imageSrc: require("../ShrimpShots/Isopod/Platin_Tung_Song.jpg"),
        name: "Platin Tung Song",
        description: '(Cubaris)',
        border: {borderImage: 'linear-gradient(#83a6dd , #150f36) 1'},
    },
    {
        imageSrc: require("../ShrimpShots/Isopod/Powder_Orange.jpg"),
        name: "Powder Orange",
        description: '(Porcellio)',
        border: {borderImage: 'linear-gradient(#83a6dd , #150f36) 1'},
    },
    {
        imageSrc: require("../ShrimpShots/Isopod/Punta_Cana.jpg"),
        name: "Punta Cana",
        description: '(Armadillidium)',
        border: {borderImage: 'linear-gradient(#83a6dd , #150f36) 1'},
    },
    {
        imageSrc: require("../ShrimpShots/Isopod/Shiro_Utsuri.jpg"),
        name: "Shiro Utsuri",
        description: '(Cubaris)',
        border: {borderImage: 'linear-gradient(#83a6dd , #150f36) 1'},
    },
    {
        imageSrc: require("../ShrimpShots/Isopod/T+_Albino.jpg"),
        name: "T+ Albino",
        description: '(Armadillidium)',
        border: {borderImage: 'linear-gradient(#83a6dd , #150f36) 1'},
    },
    {
        imageSrc: require("../ShrimpShots/Isopod/Werneri_Orange.jpg"),
        name: "Werneri Orange",
        description: '(Armadillidium)',
        border: {borderImage: 'linear-gradient(#83a6dd , #150f36) 1'},
    },
    {
        imageSrc: require("../ShrimpShots/Isopod/White_Pigeon.jpg"),
        name: "White Pigeon",
        description: '(Porcellio)',
        border: {borderImage: 'linear-gradient(#83a6dd , #150f36) 1'},
    },
]

export default shrimp;